### Test REST list orders
GET http://localhost:8080/order

###

### Teste para criar uma nova ordem (REST)
POST http://localhost:8080/order
Content-Type: application/json

{
  "item": "Laptop",
  "quantity": 2,
  "price": 1500.00
}

###

### Teste para listar ordens (GraphQL)
POST http://localhost:8081/graphql
Content-Type: application/json

{
  "query": "{ listOrders { id item quantity price } }"
}
